### ISSUE TITLE
Generalize the setup script to run for various cases

### ISSUE THREAD

**Issue by mspringborn** [mspringborn/salmonids#1]
functionalize FDP

**Comment by amandafaig** [comment]
test

**Comment by amandafaig** [comment]
Test

sent from my phone

**Comment by amandafaig** [comment]
Ok, so it's pretty much there.  The script right now *can* do:

* accept up to 1 autocorrelated shock (must be in first dimension)
* accept any finite number of populations (any dimension)
* accept any finite number of stocks per population (i.e. any finite number of dimensions in general)

The script is lacking:

* graphics for 3D+ -- too be added later, will make new issue
* ability to use more than one action variable, though the language was written with the assumption I'd go in and update that later, too.
* only output right now is value function, will update so policy function is also an output.

**Files**

1. FDP_main_script.m  
  * This is the main script.  Open this up first.  
  * This is where you change any of your variables that control price, bio, grid size, iteration numbers, etc.. 
  * This is also where you write the parametric regressions that will be used.  Right now I only assume you will ever use two: 'valuefun' and 'valuefun_late'.  That said, you can write them however you want.
1. stoch_process.m
  * This is where you write the stochastic process.  I considered putting it directly in FDP_main_script but it sure is an ugly, long piece of code.  Anyway, what needs to come out of stoch_process is:
  * fz -- vector of the effect each z will have
  * CDF_shock -- either a transition matrix (if autocorrelated) or simply a CDF (if uncorrelated) used to draw the next shock in the program.
  * next task will be to remove redundancy in setup files--I'm going to keep this file and get rid of sc_setup_stoch_state.m and offgrid_setup.m, since those are both very specific and stoch_process is general.
3. cgamFDP.R
  * Untouched from before, but something that is important to remember goes with the program.
4. offgrid_FDP_function.m
  * This is the actual FDP function.  


**Mike**
Mike, it'd be great if you could run FDP_main_script.m either first or side by side with salmon_offgrid_FDP.m  I tried to run them side by side to completion but unfortunately the code that lets the program talk to R on a mac was partially cannibalized into the code that lets matlab talk R on a PC and is missing several necessary lines of code.  Since one of my tasks is to edit the code for PC so that it works on a mac, it seems silly for me to spend time digging around to find an old version that did work to edit this back.  

Right now both programs are seeded three times--once before each random generating number (had to do that because the order of the random draws has changed somewhat).  The two should be the exact same. Before nonparametric, I checked this, and it was true at every point--the state, shock, and value function were always identical.

Once we're satisfied FDP_main_script/offgrid_FDP_function works, we should retire salmon_offgrid_FDP since it's just an old redundant copy.  We should also remove the seeds.  Let me know when you're done going through the new files and I'll do both of those things.

**Comment by mspringborn** [comment]
Just tried to run this.  
* The pointer to my copy of R no longer works.  Did you change the location of R from the version I last used?  
* The value function moves mostly out of the figure.

**Comment by amandafaig** [comment]
Hey Mike,
I didn't change the location of R... let me look into this.

**Comment by amandafaig** [comment]
Does salmon_offgrid_FDP still works for you?  

-------------------------------------------------------------------
Amanda Faig
Ph.D. Candidate
Agricultural and Resource Economics, UC Davis
530 848 0938
afaig@ucdavis.edu

**Comment by mspringborn** [comment]
Yes, salmon_offgrid_FDP  is running, including the non-param estimation.

**Comment by amandafaig** [comment]
Ok thanks, that’s really helpful to know.


-------------------------------------------------------------------
Amanda Faig
Ph.D. Candidate
Agricultural and Resource Economics, UC Davis
530 848 0938
afaig@ucdavis.edu

**Comment by mspringborn** [comment]
The nonparametric regression in offgrid_FDP_function.m should be a function, e.g. predict_cgamR_fun.m

lines 359-398 would go to the function i think 

The call to it would look something like this: 
Vpred       = predict_cgamR_fun(x,y,w);

**Comment by mspringborn** [comment]
Let me know when the functionalized version is ready to try again.

**Comment by amandafaig** [comment]
THat’s the weird thing.. I couldn’t figure out why it’ snot running.. they’re actually identical once it gets to the nonparametric portion.

I’m working on making the nonparametric portion of the code run on a Mac… that way I can debug effectively.

-------------------------------------------------------------------
Amanda Faig
Ph.D. Candidate
Agricultural and Resource Economics, UC Davis
530 848 0938
afaig@ucdavis.edu

**Comment by amandafaig** [comment]
OK... try now.  I changed the R code so that it can run on a mac, and for me both programs run the same.  It's still not the best... I get a lot of "this should never happen!" errors, but I also get a lot of successful model 1 and model 2 runs.

**Comment by mspringborn** [comment]
The old script version works well.

I just tried the functionalized version again and R/nonparam/cgam executes but not as it should.  "This should never happen" should never happen.

**Comment by amandafaig** [comment]
Oh, I think I figured it out!  In the functionalized version I had to change the regressions to absolute the shock, rather than have it occur automatically.  That must be screwing up the nonparametric regression.

I’ve edited that.. let me know how it works.  
-------------------------------------------------------------------
Amanda Faig
Ph.D. Candidate
Agricultural and Resource Economics, UC Davis
530 848 0938
afaig@ucdavis.edu

**Comment by mspringborn** [comment]
Tried it but it failed.

**Comment by amandafaig** [comment]
Can you elaborate on what that means?  How do the output differ?

**Comment by mspringborn** [comment]
The functionalized version nonparam call generates "...this should never happen" errors and the value function becomes fixed, linear, and with lines crossing.  The nonparam regression is just not working (though R is being accessed in some form).

**Comment by amandafaig** [comment]
Oh. Yeah I figured it out this time, I'm pretty sure.  Thanks, that description helped.
In the functionalized version I switched shock to be the first parameter and stock to be the second.  Of course the R code isn't working.  Run it again when you have a chance, but I feel pretty good about this...

**Comment by mspringborn** [comment]
Still failing.  
![image](https://cloud.githubusercontent.com/assets/12819222/8367486/6fc30658-1b53-11e5-9533-11b09c8823ca.png)

**Comment by mspringborn** [comment]
Can you run this on the rack to see how it works on the pc?

**Comment by amandafaig** [comment]
Ok.  So while I couldn't get on the rack, after fixing the code so matlab/R can talk properly on my mac (see that issue--I got nonstop "nonprime model 1 successful") I saw what you saw--the functionalized version didn't work very well at all.

In the end, I found a couple things that were wrong while debugging.

1. in the original code, there was nothing that switched "RscriptFileName" back to the first form--that has been remedied.  What this means is that, in the original code, if cgamFDP.R failed once and switched to no2ndorderintx_cgamFDP.R, from then on it ran no2ndorderintx_cgamFDP.R.

2. In the functionalized version, since I made a naming mistake, it actually went from "nonparam_FDP.R" to "nonparam_FDP.R_nointx".  Obviously this couldn't work!!!  Now it goes to "nointx_nonparam_FDP.R", which works...

So now everything should be in working order--it is for me.  It's not as clean as it used to seem, but the key word is "seem", since before we were running the regression with no interactions the majority of the time.

Now they should both give output that looks something like this:

![screen shot 2015-06-26 at 8 12 43 pm](https://cloud.githubusercontent.com/assets/7494361/8390366/b6d84c0a-1c44-11e5-9f7d-c80724fe65a7.png)

**Comment by mspringborn** [comment]
Cool.  Nice catch.  I'll give it a go.  

Remember, I'd like to switch over time to handling cases with "switch" versus if (e.g. for things like comptype).  E.g.: 
%% Handling cases
growthfun='l'; 
switch lower(growthfun)
  case 'l'
    G = @(x) x+r*x.*(1-x/K);                 % logistic growth function
  case 'b'
    G = @(x) (1+r)*x./(1+r/K*x);             % Beverton-Holt growth function
  case 'r'
    G = @(x) (1+r)*x.*exp(-(log(1+r)/K)*x);  % Ricker growth function
end

**Comment by mspringborn** [comment]
What's the logic here? (salmondoffgrid.m, line 343):

try writetable(FDPoutputtable,'FDPoutput_1by50.csv'); catch writetable(FDPoutputtable,'FDPoutput_1by50.csv'); end

**Comment by amandafaig** [comment]
Ok, noted.  Once you check to make sure the code is working for you I have some changes ready to be implemented.
-------------------------------------------------------------------
Amanda Faig
Ph.D. Candidate
Agricultural and Resource Economics, UC Davis
530 848 0938
afaig@ucdavis.edu

**Comment by amandafaig** [comment]
You know, I was wondering that myself.  I haven’t really touched any of your code for Matlab-R talk, since until very recently I couldn’t use them.   

in (salmon_offgrid_FDP.m):

Lines 345 to 397 were added by you so Matlab could talk to R on PCs

Lines 354, 378, and 347 were additions by me.  The first two are just the mac analog to commands on line 350 and 376, respectively, and the last was to make sure we kept going back to the concave form of the nonparametric regression.

I wasn't familiar with try/catch loops, and when I looked it up it didn’t really clarify line 343.  I considered deleting the loop, but I didn’t want to mess up your code, especially before I’d fully debugged the function version.


-------------------------------------------------------------------
Amanda Faig
Ph.D. Candidate
Agricultural and Resource Economics, UC Davis
530 848 0938
afaig@ucdavis.edu

**Comment by mspringborn** [comment]
line 343: Ok, so that was something I wrote, is what you're saying.   I didn't do a great job (or any job) with notes there.   It must have been inserted because sometimes the writetable command would fail (maybe because the object/array wasn't quite ready) and the try/catch structure provided a way to catch the error and immediately retry the command, which would by then be ok to execute (after some number of extra milliseconds).

**Comment by amandafaig** [comment]
Well, either it’s something you wrote or it’s leftover from the code you used to write it.  I wasn’t sure if it was one or the other.

Ok that makes sense.


-------------------------------------------------------------------
Amanda Faig
Ph.D. Candidate
Agricultural and Resource Economics, UC Davis
530 848 0938
afaig@ucdavis.edu
